[package]
name = "shadow-ray"
version = "0.2.8"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "25.1.1"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = false
panic = "abort"
lto = true