name: Shadow Ray Build and Verify

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  attestations: write
  actions: write

jobs:
  build-and-verify:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      # This tells the builder to look inside your contracts folder
      package_workspace_root: contracts/game
      package: shadow-ray
      release_name: "Shadow Ray Build ${{ github.sha }}"
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}