name: Build and Release

on:
  push:
    tags:
      - 'v*'  # This is the trigger StellarExpert looks for

permissions:
  id-token: write
  contents: write
  attestations: write
  actions: write

jobs:
  release:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Shadow Ray ZK-Game Contract Release'
      relative_path: 'contracts/game'
      package: 'shadow-ray'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}